version: '4.30.0'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - my_db
    networks:
      - app-network
    environment:
      - DATABASE_URL=mongodb://my_db:27017/yourdbname
      - WEBHOOK_SECRET=your-webhook-secret

  my_db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:

networks:
  app-network: